### PR TITLE
ref!: major refactor

### LINKED ISSUE #68: Errors with prettierd aren't handled
When the formatter fails the error gets written in the buffer.

```
SyntaxError: Unknown keyword or identifier. Did you mean 'import'? (1:1)
[0m[31m[1m>[22m[39m[90m 1 |[39m mport { defineStore } [36mfrom[39m [32m'pinia'[39m[33m;[39m[0m
[0m [90m   |[39m [31m[1m^[22m[39m[0m
[0m [90m 2 |[39m [36mimport[39m type {[0m
[0m [90m 3 |[39m     [33mCreateProgramContract[39m[33m,[39m[0m
[0m [90m 4 |[39m     [33mPpmProgram[39m[33m,[39m[0m
```

used config:
```lua
    {
        "nvimdev/guard.nvim",
        event = { 'BufReadPost', 'BufNewFile' },
        config = function()
            local ft = require('guard.filetype')

            ft('typescript,javascript,typescriptreact,vue'):fmt('prettierd')
            --     :lint({
            --     cmd = 'eslint',
            --     args = { '--fix' },
            --     stdin = true
            -- })

            -- Call setup() LAST!
            require('guard').setup({
                -- the only options for the setup function
                fmt_on_save = true,
                -- Use lsp if no formatter was defined for this filetype
                lsp_as_default_formatter = false,
            })
        end
    },
```

### PR DESCRIPTION
**Pull request by xiaoshihou514**
closes #68 #86 #123 #109 #76 #141 #111
## changes
- [x] remove uv.spawn wrapper in favour of vim.system
- [x] `do_lint` now respects *all* config fields
- [x] linter can now use lnum_end and col_end
- [x] added step by step tutorial for advanced usage
- [x] remove all version checking code, only supports 0.10+ from now on
- [x] apply exepath fix for windows

## internal changes
- [x] events now contains truly all autocmd related functions
- [x] utils now contains execution checking functions
- [x] use custom simpler table copy

### CODE REVIEW

File: lua/guard/events.lua [hunk 1]
```diff
@@ -1,12 +1,25 @@
 local api = vim.api
+local uv = vim.uv
```
Comment (glepnir) [inline lua/guard/events.lua:2]:
```suggestion
local api,uv = vim.api,vim.uv
```

File: lua/guard/util.lua [hunk 2]
```diff
@@ -65,7 +65,7 @@ function util.get_clients(bufnr, method)
   if vim.version().minor >= 10 then
```
Comment (glepnir) [inline lua/guard/util.lua:65]: we can only support 0.10

**Comment by glepnir** [comment]
the main idea of there i think we can now remove the custom spawn logic and move to vim.system with coroutine wrapper.

**Comment by xiaoshihou514** [comment]
I can try...

**Comment by xiaoshihou514** [comment]
@glepnir The main thread is still blocked on `api.nvim_buf_set_lines(...)`, any way around it?

**Comment by xiaoshihou514** [comment]
TODO: make linters support all config fields

**Comment by glepnir** [comment]
seems like need more tast cases.

**Comment by xiaoshihou514** [comment]
ok

File: lua/guard/lsp.lua [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+    end
+  end
+
+  vim.lsp.buf.format({
+    bufnr = buf,
+    range = range,
+    async = true,
+  })
+
+  return coroutine.yield()
```
Comment (glepnir) [inline lua/guard/lsp.lua:48]:
```suggestion
  return (coroutine.yield())
```

File: lua/guard/util.lua [hunk 4]
```diff
@@ -12,9 +10,9 @@ function util.get_prev_lines(bufnr, srow, erow)
   return res
 end
 
-function util.get_lsp_root(buf)
+function M.get_lsp_root(buf)
```
Comment (glepnir) [inline lua/guard/util.lua:13]: add return lua doc

File: lua/guard/util.lua [hunk 5]
```diff
@@ -61,21 +55,98 @@ function util.range_from_selection(bufnr, mode)
...
+  elseif config.find and not find(startpath, config.find, root_dir) then
+    return false
+  end
+  return true
+end
+
+---@return string, string, string, string
+function M.buf_get_info(buf)
+  local fname = vim.fn.fnameescape(api.nvim_buf_get_name(buf))
+  ---@diagnostic disable-next-line: param-type-mismatch
```
Comment (glepnir) [inline lua/guard/util.lua:122]: hmmm i think we should handle these add a ingore luadoc comment.

File: lua/guard/util.lua [hunk 6]
```diff
@@ -61,21 +55,98 @@ function util.range_from_selection(bufnr, mode)
...
+  local startpath = vim.fn.expand(fname, ':p:h')
+  local root_dir = M.get_lsp_root()
+  ---@diagnostic disable-next-line: undefined-field
+  local cwd = root_dir or vim.uv.cwd()
+  ---@diagnostic disable-next-line: return-type-mismatch
```
Comment (glepnir) [inline lua/guard/util.lua:127]: ditto

File: lua/guard/util.lua (hunk 5 above)
Comment (xiaoshihou514) [reply lua/guard/util.lua:122]: lua_ls thought this is table.expand instead of vim.fn.expand

File: lua/guard/util.lua (hunk 6 above)
Comment (xiaoshihou514) [reply lua/guard/util.lua:127]: lua_ls does not know about vim.uv

File: lua/guard/util.lua (hunk 5 above)
Comment (glepnir) [reply lua/guard/util.lua:122]: need .luarc.json and config it.

Comment (xiaoshihou514) [reply lua/guard/util.lua]: update: lua_ls is correct and we are missing an argument

File: lua/guard/util.lua [hunk 7]
```diff
@@ -135,8 +135,7 @@ end
 ---@return string, string, string, string
 function M.buf_get_info(buf)
   local fname = vim.fn.fnameescape(api.nvim_buf_get_name(buf))
-  ---@diagnostic disable-next-line: param-type-mismatch
-  local startpath = vim.fn.expand(fname, ':p:h')
+  local startpath = vim.fn.expand(fname, false, ':p:h')
```
Comment (glepnir) [inline lua/guard/util.lua:138]: why not fnamemodify

Comment (xiaoshihou514) [reply lua/guard/util.lua:138]: How should I change that?

File: lua/guard/spawn.lua [hunk 8]
```diff
@@ -1,119 +1,25 @@
...
+    cwd = config.cwd,
+    env = config.env,
+    timeout = config.timeout,
+  }, function(result)
+    if result.code ~= 0 and #result.stderr > 0 then
+      -- error
+      coroutine.resume(co, result)
     else
-      coroutine.resume(co, table.concat(chunks))
+      coroutine.resume(co, result.stdout)
```
Comment (glepnir) [inline lua/guard/spawn.lua:16]: there should keep as before. if stream data overflow buffer this callback will run more than once.

File: lua/guard/events.lua [hunk 9]
```diff
@@ -1,12 +1,24 @@
...
-local function watch_ft(fts)
+function M.attach_to_buf(buf)
+  api.nvim_create_autocmd('BufWritePre', {
+    group = group,
+    buffer = buf,
+    callback = function(opt)
+      if not vim.bo[opt.buf].modified then
+        return
+      end
+      require('guard.format').do_fmt(opt.buf)
```
Comment (glepnir) [inline lua/guard/events.lua:13]: thought can we get  changedtick in there and passed into the do_fmt for later check

Comment (xiaoshihou514) [reply lua/guard/events.lua:13]: I think the current setup offers a nice API, also it makes sense we get changetick right before we begin formatting. I don't think the user would need such a strict contract (that `GuardFmt` calculates the change tick _immediately_)

File: lua/guard/spawn.lua (hunk 8 above)
Comment (xiaoshihou514) [reply lua/guard/spawn.lua:16]: You mean we should split it here?

Comment (glepnir) [reply lua/guard/spawn.lua:16]: collect stdout and only resume when is nil that mean no data in buffer.

File: lua/guard/events.lua (hunk 9 above)
Comment (glepnir) [reply lua/guard/events.lua:13]: aha. make sense.

File: lua/guard/events.lua [hunk 10]
```diff
@@ -44,14 +57,55 @@ local function create_lspattach_autocmd(fmt_on_save)
...
+    pattern = ft,
+    group = group,
+    callback = function(args)
+      local cb = function(opt)
+        if debounce_timer then
+          debounce_timer:stop()
+          debounce_timer = nil
+        end
+        ---@diagnostic disable-next-line: undefined-field
+        debounce_timer = uv.new_timer()
```
Comment (glepnir) [inline lua/guard/events.lua:78]: type inline ` --[[uv_timer_t]]`

File: lua/guard/format.lua [hunk 11]
```diff
@@ -49,158 +44,203 @@ local function update_buffer(bufnr, prev_lines, new_lines, srow, erow)
...
+    return util.should_run(config, buf, startpath, root_dir)
+  end, fmt_configs)
+
+  -- check if all cmds executable
+  local non_excutable = vim.tbl_filter(function(config)
+    return config.cmd and vim.fn.executable(config.cmd) ~= 1
+  end, fmt_configs)
+
+  if #non_excutable > 0 then
+    error(table.concat(
```
Comment (glepnir) [inline lua/guard/format.lua:100]: use format will more readable.

File: lua/guard/format.lua [hunk 12]
```diff
@@ -49,158 +44,203 @@ local function update_buffer(bufnr, prev_lines, new_lines, srow, erow)
...
+      vim.tbl_map(function(config)
+        return config.cmd
+      end, non_excutable),
+      ', '
+    ) .. ' not executable')
+  end
+
+  -- filter out "pure" and "impure" formatters
+  local pure = vim.iter(vim.tbl_filter(function(config)
```
Comment (glepnir) [inline lua/guard/format.lua:109]: avoid hash loolup, if a function we use very frequently. it's better define alias on top. also api.nvim_create_autocmd

**Comment by glepnir** [comment]
test cases for new vim.spawn wrapper. single tool multiple tools etc case.

File: lua/guard/format.lua (hunk 12 above)
Comment (xiaoshihou514) [reply lua/guard/format.lua:109]: ok

**Comment by xiaoshihou514** [comment]
> test cases for new vim.spawn wrapper. single tool multiple tools etc case.

Do I just assert true like in previous test?

**Comment by glepnir** [comment]
that's too simple It's better pass some codes as stdin then check result.

File: lua/guard/events.lua (hunk 10 above)
Comment (xiaoshihou514) [reply lua/guard/events.lua:78]: The problem is that vim.uv does not have any annotations

File: lua/guard/format.lua [hunk 13]
```diff
@@ -1,24 +1,20 @@
...
-  end
-
-  for _, pattern in pairs(util.as_table(patterns)) do
-    if fname:find(pattern) then
-      return true
-    end
-  end
-  return false
-end
+local iter, filter = vim.iter, vim.tbl_filter
```
Comment (glepnir) [inline lua/guard/format.lua:17]: filter can use iter.any instead

Comment (xiaoshihou514) [reply lua/guard/format.lua:17]: Then we won't be able to warn about all non executables

File: lua/guard/lsp.lua [hunk 14]
```diff
@@ -0,0 +1,51 @@
...
+  -- use a temporary buffer to apply edits
+  local scratch = api.nvim_create_buf(false, true)
+  local apply = vim.lsp.util.apply_text_edits
+  local n_edits = #clients
+  api.nvim_buf_set_lines(scratch, 0, -1, false, vim.split(acc, '\r?\n'))
+  local line_offset = range and range.start[1] - 1 or 0
+
+  ---@diagnostic disable-next-line: duplicate-set-field
+  vim.lsp.util.apply_text_edits = function(text_edits, bufnr, offset_encoding)
+    if bufnr ~= buf then
```
Comment (glepnir) [inline lua/guard/lsp.lua:24]: what's the meaning of here . `bufnr ~= buf` then apply texteidts ?

**Comment by yebt** [comment]
<3
I'm going to love this plugin, thank you very much

File: lua/guard/events.lua [hunk 15]
```diff
@@ -44,14 +73,69 @@ local function create_lspattach_autocmd(fmt_on_save)
...
+        M.attach_to_buf(args.buf)
+      end
+    end,
+  })
+end
+
+local debounce_timer = nil
+function M.register_lint(ft, events)
+  -- check if all cmds executable before registering formatter
+  local non_excutable = filter(function(config)
```
Comment (glepnir) [inline lua/guard/events.lua:85]: remove vim.tlb_filter just iter.any like

```lua
 iter(require('guard.filetype')[ft].linter):any(function(config) 
      if  config.cmd and vim.fn.executable(config.cmd) ~= 1 then
           error()
      end
 end)
 ```

Comment (xiaoshihou514) [reply lua/guard/events.lua:85]: Well, then we only get to warn about one non executable...

Comment (glepnir) [reply lua/guard/events.lua:85]: :help lua-error

when you invoke `error` function the code below of this line will never run.

```lua
error('an error')
print('hello')
```

Comment (xiaoshihou514) [reply lua/guard/events.lua:85]: sry, I meant to use util.error

File: lua/guard/util.lua [hunk 16]
```diff
@@ -61,21 +60,112 @@ function util.range_from_selection(bufnr, mode)
...
+    ignore_patterns = c.ignore_patterns,
+    ignore_error = c.ignore_error,
+    find = c.find,
+    env = c.env,
+    timeout = c.timeout,
+    parse = c.parse,
+  }
+end
+
+function M.error(msg)
```
Comment (glepnir) [inline lua/guard/util.lua:167]: this is too simply . if we want do error handling . need check which error should be stop run script. maybe can give it a type E or W if E we invoke error otherwise just like this.

File: lua/guard/events.lua [hunk 17]
```diff
@@ -1,12 +1,33 @@
-local api = vim.api
+local api, uv = vim.api, vim.uv
 local group = api.nvim_create_augroup('Guard', { clear = true })
-local ft_handler = require('guard.filetype')
-local format = require('guard.format')
+local au = api.nvim_create_autocmd
+local filter = vim.tbl_filter
```
Comment (glepnir) [inline lua/guard/events.lua:4]:
```suggestion
```

File: lua/guard/util.lua (hunk 16 above)
Comment (xiaoshihou514) [reply lua/guard/util.lua]: That part of the logic is handled on the caller side

File: lua/guard/format.lua [hunk 18]
```diff
@@ -90,18 +90,12 @@ local function do_fmt(buf)
...
-        return config.cmd
-      end, non_excutable),
-      ', '
-    )))
-  end
+  iter(require('guard.filetype')[filetype].formatter):any(function(config)
+    if config.cmd and vim.fn.executable(config.cmd) ~= 1 then
+      error(config.cmd .. ' not executable', 1)
+    end
+    return true
```
Comment (glepnir) [inline lua/guard/format.lua:97]: redundant

Comment (xiaoshihou514) [reply lua/guard/format.lua:97]: lua_ls would complain otherwise

**Review by glepnir — APPROVED** [review]
nice work. some edge cases can fix in later.

**Comment by anna328p** [comment]
hi hello you accidentally started writing double newlines to the linter (guard.nvim adds a newline to the end of each line in https://github.com/nvimdev/guard.nvim/blob/main/lua/guard/util.lua#L9-L16, and then nvim's SystemObj:write() adds a newline to the end of every line it writes, see https://github.com/neovim/neovim/blob/5331f87f6145f705c73c5c23f365cecb9fbc5067/runtime/lua/vim/_system.lua#L122-L125) which means the linter gets line numbers wrong and keeps complaining about there being too many newlines.

**Comment by xiaoshihou514** [comment]
> hi hello you accidentally started writing double newlines to the linter (guard.nvim adds a newline to the end of each line in https://github.com/nvimdev/guard.nvim/blob/main/lua/guard/util.lua#L9-L16, and then nvim's SystemObj:write() adds a newline to the end of every line it writes, see https://github.com/neovim/neovim/blob/5331f87f6145f705c73c5c23f365cecb9fbc5067/runtime/lua/vim/_system.lua#L122-L125) which means the linter gets line numbers wrong and keeps complaining about there being too many newlines.

Oh wow nice catch! That explains why clippy always reports the double amount of line number.

I will push a fix tonight after some more testing.
